# -*- coding: utf-8 -*-
"""
/***************************************************************************
 windForecastRouting
                                 A QGIS plugin
 sailing routing by wind forecast
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-03-30
        copyright            : (C) 2021 by enrico ferreguti
        email                : enricofer@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'enrico ferreguti'
__date__ = '2021-03-30'
__copyright__ = '(C) 2021 by enrico ferreguti'

import os 
import site
import sys

sys.path.append(os.path.dirname(__file__))

site.addsitedir(os.path.join(os.path.dirname(__file__),'extlibs'))

if not hasattr(sys, 'argv'):
    sys.argv  = ['']


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load windForecastRouting class from file windForecastRouting.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .wind_forecast_routing import windForecastRoutingPlugin
    return windForecastRoutingPlugin(iface)
