# -*- coding: utf-8 -*-

"""
/***************************************************************************
 windForecastRouting
                                 A QGIS plugin
 sailing routing by wind forecast
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-03-30
        copyright            : (C) 2021 by enrico ferreguti
        email                : enricofer@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'enrico ferreguti'
__date__ = '2021-03-30'
__copyright__ = '(C) 2021 by enrico ferreguti'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from PyQt5 import QtGui, QtWidgets, uic
from PyQt5.QtCore import QUrl, QJsonDocument
from PyQt5.QtNetwork import QNetworkRequest

from qgis.core import (QgsProcessing,
                       QgsCoordinateTransform,
                       QgsCoordinateReferenceSystem,
                       QgsFeatureSink,
                       QgsMeshLayer,
                       QgsProject,
                       QgsNetworkAccessManager,
                       QgsVectorLayer,
                       QgsField,
                       QgsFields,
                       QgsRectangle,
                       QgsFeature,
                       QgsGeometry,
                       QgsWkbTypes,
                       QgsInterval,
                       QgsPointXY,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterPoint,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterMeshLayer,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterVectorLayer,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterDateTime,
                       QgsProcessingParameterVectorDestination)

import processing
import math
import os
from datetime import datetime, timedelta
import dateutil
import requests

class windForecastLaunchAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    START_POINT = 'START_POINT'
    END_POINT = 'END_POINT'
    POLAR = 'POLAR'
    START_TIME = 'START_TIME'
    GRIB_OUTPUT = 'GRIB_OUTPUT'
    OUTPUT_WAYPOINTS = 'OUTPUT_WAYPOINTS'
    OUTPUT_ROUTE = 'OUTPUT_ROUTE'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        #http://jieter.github.io/orc-data/site/
        self.polars_dir = os.path.join(os.path.dirname(__file__),"polar_files")
        self.polars = {}
        for polar_file in os.listdir(self.polars_dir):
            polar_name, ext = os.path.splitext(polar_file)
            if ext == '.pol':
                self.polars[polar_name] = polar_file
        self.polar_names = list(self.polars.keys())
        self.polar_names.sort()

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(QgsProcessingParameterEnum(self.POLAR, 'Polar (Courtesy of seapilot.com)', options=self.polar_names, defaultValue=None, allowMultiple=False))
        self.addParameter(QgsProcessingParameterPoint(self.START_POINT, self.tr('Start point')))
        self.addParameter(QgsProcessingParameterPoint(self.END_POINT, self.tr('End point')))
        self.addParameter(QgsProcessingParameterDateTime(self.START_TIME, self.tr('Time of departure')))
        self.addParameter(QgsProcessingParameterFileDestination(self.GRIB_OUTPUT, self.tr('grib_file')))
        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterVectorDestination(
                self.OUTPUT_WAYPOINTS,
                self.tr('Waypoints Output layer'),
                createByDefault=True
            )
        )
        self.addParameter(
            QgsProcessingParameterVectorDestination(
                self.OUTPUT_ROUTE,
                self.tr('Route Output layer'),
                createByDefault=True
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        polar = self.parameterAsEnum(parameters, self.POLAR, context)
        start_time = self.parameterAsDateTime(parameters, self.START_TIME, context)
        grib_crs = QgsCoordinateReferenceSystem("EPSG:4326")
        start_point = self.parameterAsPoint(parameters, self.START_POINT, context, crs=grib_crs)
        end_point = self.parameterAsPoint(parameters, self.END_POINT, context, crs=grib_crs)
        grib_output = self.parameterAsFile(parameters, self.GRIB_OUTPUT, context)

        track = ((start_point.y(), start_point.x()), (end_point.y(), end_point.x()))
        geo_context = QgsRectangle(start_point.x(),start_point.y(), end_point.x(),end_point.y())
        track_dist = QgsPointXY(start_point.x(),start_point.y()).sqrDist(end_point.x(), end_point.y())
        geo_context.grow( (track_dist/2 ) if track_dist < 1 else 0.5 ) #limit grow to 0.5 degree
        output_route = self.parameterAsVectorLayer(parameters, self.OUTPUT_ROUTE, context)
        output_waypoints = self.parameterAsVectorLayer(parameters, self.OUTPUT_WAYPOINTS, context)

        params = {
            "bottom": geo_context.yMinimum(),
            "top": geo_context.yMaximum(),
            "left": geo_context.xMinimum(),
            "right":geo_context.yMaximum()
        }

        print (params)

        url = 'http://grbsrv.opengribs.org/getmygribs2.php/?osys=Unknown&ver=1.2.4&la1={bottom}&la2={top}&lo1={left}&lo2={right}&model=icon_eu_p06_&wmdl=none&intv=1&days=5&cyc=last&par=W%3B&wpar='.format(**params)
        print (url)
        manager = QgsNetworkAccessManager.instance()
        request = QNetworkRequest()
        request.setUrl(QUrl(url))
        rawReplyObject = manager.blockingGet(request)
        j = QJsonDocument.fromJson(rawReplyObject.content())
        replyObject = j.toVariant()
        print (rawReplyObject.content())
        if replyObject["status"]:
            #mesh_name = QUrl(replyObject["message"]["url"]).fileName()
            #targetFile = os.path.join(os.path.dirname(__file__),'gribs',mesh_name)
            #request.setUrl(QUrl(replyObject1["message"]["url"]))
            #replyObject2 = manager.blockingGet(request)

            download_params = {
                'URL': replyObject["message"]["url"],
                'OUTPUT': grib_output
            }

            print (download_params)
            output_download = processing.run('native:filedownloader', download_params, context=context, feedback=feedback, is_child_algorithm=True)
            #with open(targetFile, 'wb') as f:
            #    f.write(replyObject.content())
            #self.status_label.setText("Downloaded: "+targetFile)
            #self.iface.messageBar().clearWidgets()
            #self.iface.messageBar().pushMessage("QGribDownloader", "Downloaded: " + targetFile, level=Qgis.Success, duration=9999)
            #meshLayer = QgsMeshLayer(output_download['OUTPUT'], QUrl(replyObject["message"]["url"]).fileName(), "mdal")
            #QgsProject.instance().addMapLayer(meshLayer)
            #self.iface.mapCanvas().setDestinationCrs(meshLayer.crs())
        else:
            print ("ERROR", replyObject)

        routing_params = {
            'START_POINT': start_point,
            'END_POINT': end_point,
            'POLAR': polar,
            'GRIB': output_download['OUTPUT'],
            'WIND_DATASET_INDEX': 0,
            'START_TIME': start_time,
            'OUTPUT_WAYPOINTS': QgsProcessing.TEMPORARY_OUTPUT,
            'OUTPUT_ROUTE': QgsProcessing.TEMPORARY_OUTPUT,
        }

        print (routing_params)

        output_routing = processing.run('sailtools:windrouting', routing_params, context=context, feedback=feedback, is_child_algorithm=True)

        output_routing[self.GRIB_OUTPUT] = output_download['OUTPUT']

        return output_routing

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'windroutinglaunch'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return 'windrouting launch'

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr('Sail tools')

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'sailtools'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return windForecastLaunchAlgorithm()
